In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
directory  = "/media/sony/0CA83E99A83E80EE/Chris/Bocconi/Thesis/Data_copy/Data/"

In [3]:
df_main = pd.read_csv(directory +'merged_COPY_FINAL4.csv')

In [4]:
df_main.columns

Index(['home', 'host', 'year', 'fdi', 'home_code', 'host_code', 'region',
       'income_group', 'scoreproced', 'minorinvest', 'enfcontract', 'paytax',
       'minorinvest_lag', 'diff_minorinvest', 'distance', 'uncertainty',
       'home_gdp', 'host_gdp', 'couprisk', 'couprisk_lag', 'pt_attempt',
       'pt_attempt_lag', 'prev_conflict', 'prev_conflict_lag', 'pctile_risk',
       'pctile_risk_lag', 'diff_couprisk', 'fdi_lag', 'diff_fdi', 'export',
       'home_EU', 'home_eurozone', 'host_EU', 'host_eurozone', 'EU_partner',
       'eurozone_partner', 'home_asean', 'host_asean', 'home_mercosour',
       'host_mercosour', 'asean_partner', 'mercosour_partner', 'tariff_avg',
       'tariff_w_avg', 'uncertainty_lag', 'uncertainty_lag2',
       'home_gdp_capita', 'host_gdp_capita', 'partner_directed', 'partner',
       'home_OECD', 'host_OECD', 'OECD_partner', 'home_north', 'host_north',
       'north-north', 'north-south', 'south-north', 'south-south', 'home_lock',
       'host_lock', 'trade_lock', 'lang'],
      dtype='object')

In [5]:
df_main['union_partner'] = df_main[['EU_partner','asean_partner',
                                    'mercosour_partner']].apply(lambda x: int(1)if x[0]== 1 or x[1]==1 or x[2]==1 
                                                                else int(0), axis =1)

In [6]:
df_main[df_main['union_partner'] ==1]

,home,host,year,fdi,home_code,host_code,region,income_group,scoreproced,minorinvest,...,host_north,north-north,north-south,south-north,south-south,home_lock,host_lock,trade_lock,lang,union_partner
35900,Brazil,Argentina,1993,NaN,BRA,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,0,1
36016,Paraguay,Argentina,1993,NaN,PRY,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,1,0,1,1,1
36073,Uruguay,Argentina,1993,NaN,URY,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,1,1
36105,Brazil,Argentina,1994,NaN,BRA,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,0,1
36221,Paraguay,Argentina,1994,NaN,PRY,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,1,0,1,1,1
36278,Uruguay,Argentina,1994,NaN,URY,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,1,1
36310,Brazil,Argentina,1995,NaN,BRA,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,0,1
36426,Paraguay,Argentina,1995,NaN,PRY,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,1,0,1,1,1
36483,Uruguay,Argentina,1995,NaN,URY,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,1,1
36515,Brazil,Argentina,1996,NaN,BRA,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,0,1
36631,Paraguay,Argentina,1996,NaN,PRY,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,1,0,1,1,1
36688,Uruguay,Argentina,1996,NaN,URY,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,1,1
36720,Brazil,Argentina,1997,NaN,BRA,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,0,1
36836,Paraguay,Argentina,1997,NaN,PRY,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,1,0,1,1,1
36893,Uruguay,Argentina,1997,NaN,URY,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,1,1
36925,Brazil,Argentina,1998,NaN,BRA,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,0,1
37041,Paraguay,Argentina,1998,NaN,PRY,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,1,0,1,1,1
37098,Uruguay,Argentina,1998,NaN,URY,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,1,1
37130,Brazil,Argentina,1999,NaN,BRA,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,0,1
37246,Paraguay,Argentina,1999,NaN,PRY,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,1,0,1,1,1
37303,Uruguay,Argentina,1999,NaN,URY,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,1,1
37335,Brazil,Argentina,2000,NaN,BRA,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,0,1
37451,Paraguay,Argentina,2000,NaN,PRY,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,1,0,1,1,1
37508,Uruguay,Argentina,2000,NaN,URY,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,1,1
37540,Brazil,Argentina,2001,0.0,BRA,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,0,1
37656,Paraguay,Argentina,2001,0.0,PRY,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,1,0,1,1,1
37713,Uruguay,Argentina,2001,0.0,URY,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,1,1
37745,Brazil,Argentina,2002,0.0,BRA,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,0,1
37861,Paraguay,Argentina,2002,0.0,PRY,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,1,0,1,1,1
37918,Uruguay,Argentina,2002,0.0,URY,ARG,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1039699,Philippines,Viet Nam,2014,NaN,PHL,VNM,East Asia & Pacific,Lower middle income,80.0,40.835,...,0,0,0,0,1,0,0,0,0,1
1039718,Singapore,Viet Nam,2014,NaN,SGP,VNM,East Asia & Pacific,Lower middle income,80.0,40.835,...,0,0,1,0,0,0,0,0,0,1
1039736,Thailand,Viet Nam,2014,NaN,THA,VNM,East Asia & Pacific,Lower middle income,80.0,40.835,...,0,0,0,0,1,0,0,0,0,1
1039789,Brunei Darussalam,Viet Nam,2015,NaN,BRN,VNM,East Asia & Pacific,Lower middle income,80.0,45.000,...,0,0,0,0,1,0,0,0,0,1
1039793,Cambodia,Viet Nam,2015,NaN,KHM,VNM,East Asia & Pacific,Lower middle income,80.0,45.000,...,0,0,0,0,1,0,0,0,0,1
1039844,Indonesia,Viet Nam,2015,NaN,IDN,VNM,East Asia & Pacific,Lower middle income,80.0,45.000,...,0,0,0,0,1,0,0,0,0,1
1039859,Lao People's Dem. Rep.,Viet Nam,2015,NaN,LAO,VNM,East Asia & Pacific,Lower middle income,80.0,45.000,...,0,0,0,0,1,1,0,1,0,1
1039870,Malaysia,Viet Nam,2015,NaN,MYS,VNM,East Asia & Pacific,Lower middle income,80.0,45.000,...,0,0,0,0,1,0,0,0,0,1
1039883,Myanmar,Viet Nam,2015,NaN,MMR,VNM,East Asia & Pacific,Lower middle income,80.0,45.000,...,0,0,0,0,1,0,0,0,0,1
1039904,Philippines,Viet Nam,2015,NaN,PHL,VNM,East Asia & Pacific,Lower middle income,80.0,45.000,...,0,0,0,0,1,0,0,0,0,1
1039923,Singapore,Viet Nam,2015,NaN,SGP,VNM,East Asia & Pacific,Lower middle income,80.0,45.000,...,0,0,1,0,0,0,0,0,0,1
1039941,Thailand,Viet Nam,2015,NaN,THA,VNM,East Asia & Pacific,Lower middle income,80.0,45.000,...,0,0,0,0,1,0,0,0,0,1
1039994,Brunei Darussalam,Viet Nam,2016,NaN,BRN,VNM,East Asia & Pacific,Lower middle income,80.0,46.670,...,0,0,0,0,1,0,0,0,0,1
1039998,Cambodia,Viet Nam,2016,NaN,KHM,VNM,East Asia & Pacific,Lower middle income,80.0,46.670,...,0,0,0,0,1,0,0,0,0,1
1040049,Indonesia,Viet Nam,2016,NaN,IDN,VNM,East Asia & Pacific,Lower middle income,80.0,46.670,...,0,0,0,0,1,0,0,0,0,1
1040064,Lao People's Dem. Rep.,Viet Nam,2016,NaN,LAO,VNM,East Asia & Pacific,Lower middle income,80.0,46.670,...,0,0,0,0,1,1,0,1,0,1
1040075,Malaysia,Viet Nam,2016,NaN,MYS,VNM,East Asia & Pacific,Lower middle income,80.0,46.670,...,0,0,0,0,1,0,0,0,0,1
1040088,Myanmar,Viet Nam,2016,NaN,MMR,VNM,East Asia & Pacific,Lower middle income,80.0,46.670,...,0,0,0,0,1,0,0,0,0,1
1040109,Philippines,Viet Nam,2016,NaN,PHL,VNM,East Asia & Pacific,Lower middle income,80.0,46.670,...,0,0,0,0,1,0,0,0,0,1
1040128,Singapore,Viet Nam,2016,NaN,SGP,VNM,East Asia & Pacific,Lower middle income,80.0,46.670,...,0,0,1,0,0,0,0,0,0,1
1040146,Thailand,Viet Nam,2016,NaN,THA,VNM,East Asia & Pacific,Lower middle income,80.0,46.670,...,0,0,0,0,1,0,0,0,0,1
1040199,Brunei Darussalam,Viet Nam,2017,NaN,BRN,VNM,East Asia & Pacific,Lower middle income,80.0,55.000,...,0,0,0,0,1,0,0,0,0,1
1040203,Cambodia,Viet Nam,2017,NaN,KHM,VNM,East Asia & Pacific,Lower middle income,80.0,55.000,...,0,0,0,0,1,0,0,0,0,1
1040254,Indonesia,Viet Nam,2017,NaN,IDN,VNM,East Asia & Pacific,Lower middle income,80.0,55.000,...,0,0,0,0,1,0,0,0,0,1
1040269,Lao People's Dem. Rep.,Viet Nam,2017,NaN,LAO,VNM,East Asia & Pacific,Lower middle income,80.0,55.000,...,0,0,0,0,1,1,0,1,0,1
1040280,Malaysia,Viet Nam,2017,NaN,MYS,VNM,East Asia & Pacific,Lower middle income,80.0,55.000,...,0,0,0,0,1,0,0,0,0,1
1040293,Myanmar,Viet Nam,2017,NaN,MMR,VNM,East Asia & Pacific,Lower middle income,80.0,55.000,...,0,0,0,0,1,0,0,0,0,1
1040314,Philippines,Viet Nam,2017,NaN,PHL,VNM,East Asia & Pacific,Lower middle income,80.0,55.000,...,0,0,0,0,1,0,0,0,0,1
1040333,Singapore,Viet Nam,2017,NaN,SGP,VNM,East Asia & Pacific,Lower middle income,80.0,55.000,...,0,0,1,0,0,0,0,0,0,1
1040351,Thailand,Viet Nam,2017,NaN,THA,VNM,East Asia & Pacific,Lower middle income,80.0,55.000,...,0,0,0,0,1,0,0,0,0,1

In [7]:
def isNAFTA(x):
    if x[0] in ['MEX','USA', 'CAN'] and x[1] in ['MEX','USA', 'CAN'] and x[2] >= 1994:
        return int(1)
    else:
        return int(0)

In [8]:
df_main['NAFTA'] = df_main[['home_code','host_code','year']].apply(isNAFTA,axis = 1)

In [9]:
df_main[df_main['NAFTA'] ==1]

,home,host,year,fdi,home_code,host_code,region,income_group,scoreproced,minorinvest,...,north-north,north-south,south-north,south-south,home_lock,host_lock,trade_lock,lang,union_partner,NAFTA
179696,Mexico,Canada,1994,NaN,MEX,CAN,NaN,NaN,NaN,NaN,...,0,0,1,0,0,0,0,0,0,1
179777,United States,Canada,1994,NaN,USA,CAN,NaN,NaN,NaN,NaN,...,1,0,0,0,0,0,0,1,0,1
179901,Mexico,Canada,1995,NaN,MEX,CAN,NaN,NaN,NaN,NaN,...,0,0,1,0,0,0,0,0,0,1
179982,United States,Canada,1995,NaN,USA,CAN,NaN,NaN,NaN,NaN,...,1,0,0,0,0,0,0,1,0,1
180106,Mexico,Canada,1996,NaN,MEX,CAN,NaN,NaN,NaN,NaN,...,0,0,1,0,0,0,0,0,0,1
180187,United States,Canada,1996,NaN,USA,CAN,NaN,NaN,NaN,NaN,...,1,0,0,0,0,0,0,1,0,1
180311,Mexico,Canada,1997,NaN,MEX,CAN,NaN,NaN,NaN,NaN,...,0,0,1,0,0,0,0,0,0,1
180392,United States,Canada,1997,NaN,USA,CAN,NaN,NaN,NaN,NaN,...,1,0,0,0,0,0,0,1,0,1
180516,Mexico,Canada,1998,NaN,MEX,CAN,NaN,NaN,NaN,NaN,...,0,0,1,0,0,0,0,0,0,1
180597,United States,Canada,1998,NaN,USA,CAN,NaN,NaN,NaN,NaN,...,1,0,0,0,0,0,0,1,0,1
180721,Mexico,Canada,1999,NaN,MEX,CAN,NaN,NaN,NaN,NaN,...,0,0,1,0,0,0,0,0,0,1
180802,United States,Canada,1999,NaN,USA,CAN,NaN,NaN,NaN,NaN,...,1,0,0,0,0,0,0,1,0,1
180926,Mexico,Canada,2000,NaN,MEX,CAN,NaN,NaN,NaN,NaN,...,0,0,1,0,0,0,0,0,0,1
181007,United States,Canada,2000,NaN,USA,CAN,NaN,NaN,NaN,NaN,...,1,0,0,0,0,0,0,1,0,1
181131,Mexico,Canada,2001,NaN,MEX,CAN,NaN,NaN,NaN,NaN,...,0,0,1,0,0,0,0,0,0,1
181212,United States,Canada,2001,2.528410e+10,USA,CAN,NaN,NaN,NaN,NaN,...,1,0,0,0,0,0,0,1,0,1
181336,Mexico,Canada,2002,NaN,MEX,CAN,NaN,NaN,NaN,NaN,...,0,0,1,0,0,0,0,0,0,1
181417,United States,Canada,2002,1.806642e+10,USA,CAN,NaN,NaN,NaN,NaN,...,1,0,0,0,0,0,0,1,0,1
181541,Mexico,Canada,2003,NaN,MEX,CAN,NaN,NaN,NaN,NaN,...,0,0,1,0,0,0,0,0,0,1
181622,United States,Canada,2003,3.633703e+09,USA,CAN,NaN,NaN,NaN,NaN,...,1,0,0,0,0,0,0,1,0,1
181746,Mexico,Canada,2004,NaN,MEX,CAN,High income: OECD,High income,NaN,NaN,...,0,0,1,0,0,0,0,0,0,1
181827,United States,Canada,2004,3.462668e+09,USA,CAN,High income: OECD,High income,NaN,NaN,...,1,0,0,0,0,0,0,1,0,1
181951,Mexico,Canada,2005,NaN,MEX,CAN,High income: OECD,High income,NaN,NaN,...,0,0,1,0,0,0,0,0,0,1
182032,United States,Canada,2005,8.742655e+09,USA,CAN,High income: OECD,High income,NaN,NaN,...,1,0,0,0,0,0,0,1,0,1
182156,Mexico,Canada,2006,NaN,MEX,CAN,High income: OECD,High income,76.0,83.33,...,0,0,1,0,0,0,0,0,0,1
182237,United States,Canada,2006,1.911827e+10,USA,CAN,High income: OECD,High income,76.0,83.33,...,1,0,0,0,0,0,0,1,0,1
182361,Mexico,Canada,2007,NaN,MEX,CAN,High income: OECD,High income,76.0,83.33,...,0,0,1,0,0,0,0,0,0,1
182442,United States,Canada,2007,4.175775e+10,USA,CAN,High income: OECD,High income,76.0,83.33,...,1,0,0,0,0,0,0,1,0,1
182566,Mexico,Canada,2008,NaN,MEX,CAN,High income: OECD,High income,76.0,83.33,...,0,0,1,0,0,0,0,0,0,1
182647,United States,Canada,2008,2.779184e+10,USA,CAN,High income: OECD,High income,76.0,83.33,...,1,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1016835,Canada,United States,2003,7.090000e+09,CAN,USA,NaN,NaN,NaN,NaN,...,1,0,0,0,0,0,0,1,0,1
1016917,Mexico,United States,2003,2.173000e+09,MEX,USA,NaN,NaN,NaN,NaN,...,0,0,1,0,0,0,0,0,0,1
1017040,Canada,United States,2004,3.316400e+10,CAN,USA,High income: OECD,High income,NaN,NaN,...,1,0,0,0,0,0,0,1,0,1
1017122,Mexico,United States,2004,-6.290000e+08,MEX,USA,High income: OECD,High income,NaN,NaN,...,0,0,1,0,0,0,0,0,0,1
1017245,Canada,United States,2005,1.486800e+10,CAN,USA,High income: OECD,High income,NaN,NaN,...,1,0,0,0,0,0,0,1,0,1
1017327,Mexico,United States,2005,-1.900000e+07,MEX,USA,High income: OECD,High income,NaN,NaN,...,0,0,1,0,0,0,0,0,0,1
1017450,Canada,United States,2006,1.477000e+10,CAN,USA,High income: OECD,High income,64.0,83.33,...,1,0,0,0,0,0,0,1,0,1
1017532,Mexico,United States,2006,2.265000e+09,MEX,USA,High income: OECD,High income,64.0,83.33,...,0,0,1,0,0,0,0,0,0,1
1017655,Canada,United States,2007,4.386700e+10,CAN,USA,High income: OECD,High income,64.0,83.33,...,1,0,0,0,0,0,0,1,0,1
1017737,Mexico,United States,2007,2.910000e+08,MEX,USA,High income: OECD,High income,64.0,83.33,...,0,0,1,0,0,0,0,0,0,1
1017860,Canada,United States,2008,1.679400e+10,CAN,USA,High income: OECD,High income,64.0,83.33,...,1,0,0,0,0,0,0,1,0,1
1017942,Mexico,United States,2008,7.310000e+08,MEX,USA,High income: OECD,High income,64.0,83.33,...,0,0,1,0,0,0,0,0,0,1
1018065,Canada,United States,2009,3.036600e+10,CAN,USA,High income: OECD,High income,64.0,83.33,...,1,0,0,0,0,0,0,1,0,1
1018147,Mexico,United States,2009,2.469000e+09,MEX,USA,High income: OECD,High income,64.0,83.33,...,0,0,1,0,0,0,0,0,0,1
1018270,Canada,United States,2010,5.522000e+09,CAN,USA,High income: OECD,High income,64.0,83.33,...,1,0,0,0,0,0,0,1,0,1
1018352,Mexico,United States,2010,1.900000e+08,MEX,USA,High income: OECD,High income,64.0,83.33,...,0,0,1,0,0,0,0,0,0,1
1018475,Canada,United States,2011,1.866100e+10,CAN,USA,High income: OECD,High income,60.0,83.33,...,1,0,0,0,0,0,0,1,0,1
1018557,Mexico,United States,2011,2.491000e+09,MEX,USA,High income: OECD,High income,60.0,83.33,...,0,0,1,0,0,0,0,0,0,1
1018680,Canada,United States,2012,1.646000e+10,CAN,USA,High income: OECD,High income,60.0,83.33,...,1,0,0,0,0,0,0,1,0,1
1018762,Mexico,United States,2012,2.801000e+09,MEX,USA,High income: OECD,High income,60.0,83.33,...,0,0,1,0,0,0,0,0,0,1
1018885,Canada,United States,2013,NaN,CAN,USA,High income: OECD,High income,60.0,83.33,...,1,0,0,0,0,0,0,1,0,1
1018967,Mexico,United States,2013,NaN,MEX,USA,High income: OECD,High income,60.0,83.33,...,0,0,1,0,0,0,0,0,0,1
1019090,Canada,United States,2014,NaN,CAN,USA,High income: OECD,High income,60.0,73.33,...,1,0,0,0,0,0,0,1,0,1
1019172,Mexico,United States,2014,NaN,MEX,USA,High income: OECD,High income,60.0,73.33,...,0,0,1,0,0,0,0,0,0,1
1019295,Canada,United States,2015,NaN,CAN,USA,High income: OECD,High income,60.0,63.33,...,1,0,0,0,0,0,0,1,0,1
1019377,Mexico,United States,2015,NaN,MEX,USA,High income: OECD,High income,60.0,63.33,...,0,0,1,0,0,0,0,0,0,1
1019500,Canada,United States,2016,NaN,CAN,USA,High income: OECD,High income,60.0,63.33,...,1,0,0,0,0,0,0,1,0,1
1019582,Mexico,United States,2016,NaN,MEX,USA,High income: OECD,High income,60.0,63.33,...,0,0,1,0,0,0,0,0,0,1
1019705,Canada,United States,2017,NaN,CAN,USA,High income: OECD,High income,60.0,63.33,...,1,0,0,0,0,0,0,1,0,1
1019787,Mexico,United States,2017,NaN,MEX,USA,High income: OECD,High income,60.0,63.33,...,0,0,1,0,0,0,0,0,0,1

In [10]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1055750 entries, 0 to 1055749
Data columns (total 65 columns):
home                 1055750 non-null object
host                 1055750 non-null object
year                 1055750 non-null int64
fdi                  65205 non-null float64
home_code            1055750 non-null object
host_code            1055750 non-null object
region               492000 non-null object
income_group         492000 non-null object
scoreproced          432755 non-null float64
minorinvest          432755 non-null float64
enfcontract          492000 non-null float64
paytax               432755 non-null float64
minorinvest_lag      395855 non-null float64
diff_minorinvest     395855 non-null float64
distance             993550 non-null float64
uncertainty          182042 non-null float64
home_gdp             953660 non-null float64
host_gdp             953660 non-null float64
couprisk             874940 non-null float64
couprisk_lag         839680 non-null float64
pt_attempt           874940 non-null float64
pt_attempt_lag       839680 non-null float64
prev_conflict        874940 non-null float64
prev_conflict_lag    839680 non-null float64
pctile_risk          874940 non-null float64
pctile_risk_lag      839680 non-null float64
diff_couprisk        839680 non-null float64
fdi_lag              65205 non-null float64
diff_fdi             58546 non-null float64
export               377483 non-null float64
home_EU              1055750 non-null int64
home_eurozone        1055750 non-null int64
host_EU              1055750 non-null int64
host_eurozone        1055750 non-null int64
EU_partner           1055750 non-null int64
eurozone_partner     1055750 non-null int64
home_asean           1055750 non-null int64
host_asean           1055750 non-null int64
home_mercosour       1055750 non-null int64
host_mercosour       1055750 non-null int64
asean_partner        1055750 non-null int64
mercosour_partner    1055750 non-null int64
tariff_avg           437258 non-null float64
tariff_w_avg         437258 non-null float64
uncertainty_lag      169039 non-null float64
uncertainty_lag2     156036 non-null float64
home_gdp_capita      953250 non-null float64
host_gdp_capita      953250 non-null float64
partner_directed     1055750 non-null object
partner              1055750 non-null object
home_OECD            1055750 non-null int64
host_OECD            1055750 non-null int64
OECD_partner         1055750 non-null int64
home_north           1055750 non-null int64
host_north           1055750 non-null int64
north-north          1055750 non-null int64
north-south          1055750 non-null int64
south-north          1055750 non-null int64
south-south          1055750 non-null int64
home_lock            1055750 non-null int64
host_lock            1055750 non-null int64
trade_lock           1055750 non-null int64
lang                 1055750 non-null int64
union_partner        1055750 non-null int64
NAFTA                1055750 non-null int64
dtypes: float64(29), int64(28), object(8)
memory usage: 523.6+ MB

In [11]:
df_main.to_csv(directory +'merged_COPY_FINAL5.csv',index = False)

In [12]:
df_migration = pd.read_csv(directory +'bilateral_migration.csv', na_values='..')

In [13]:
df_migration.head()

,Country Origin Name,Country Origin Code,Migration by Gender Name,Migration by Gender Code,Country Dest Name,Country Dest Code,1960,1970,1980,1990,1991,1992,1993,2000,2001,2002,2003
0,Afghanistan,AFG,Total,TOT,Afghanistan,AFG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Afghanistan,AFG,Total,TOT,Albania,ALB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Afghanistan,AFG,Total,TOT,Algeria,DZA,41.0,16.0,13.0,10.0,10.0,10.0,10.0,8.0,8.0,8.0,8.0
3,Afghanistan,AFG,Total,TOT,American Samoa,ASM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,AFG,Total,TOT,Andorra,AND,0.0,0.0,2.0,5.0,5.0,5.0,5.0,6.0,6.0,6.0,6.0

In [14]:
df_migration.columns

Index(['Country Origin Name', 'Country Origin Code',
       'Migration by Gender Name', 'Migration by Gender Code',
       'Country Dest Name', 'Country Dest Code', '1960', '1970', '1980',
       '1990', '1991', '1992', '1993', '2000', '2001', '2002', '2003'],
      dtype='object')

In [15]:
df_mig_sub = df_migration[['Country Origin Code','Country Dest Code','1993','2000','2001','2002','2003']]

In [16]:
df_mig_sub.columns = ['home_code','host_code', 1993, 2000, 2001, 2002, 2003]

In [17]:
df_mig_melt = pd.melt(df_mig_sub,id_vars =['home_code','host_code'],var_name ='year', value_name ='migration')

In [18]:
df_mig_melt.year = df_mig_melt.year.astype('int64')

In [19]:
df_mig_melt

       home_code host_code  year  migration
0            AFG       AFG  1993        0.0
1            AFG       ALB  1993        0.0
2            AFG       DZA  1993       10.0
3            AFG       ASM  1993        0.0
4            AFG       AND  1993        5.0
5            AFG       AGO  1993        0.0
6            AFG       AIA  1993        0.0
7            AFG       ATG  1993        0.0
8            AFG       ARG  1993       21.0
9            AFG       ARM  1993        0.0
10           AFG       ABW  1993        0.0
11           AFG       AUS  1993     2637.0
12           AFG       AUT  1993      267.0
13           AFG       AZE  1993        0.0
14           AFG       BHS  1993        0.0
15           AFG       BHR  1993    22519.0
16           AFG       BGD  1993      144.0
17           AFG       BRB  1993        0.0
18           AFG       BLR  1993        0.0
19           AFG       BEL  1993      229.0
20           AFG       BLZ  1993        0.0
21           AFG       BEN  1993        0.0
22           AFG       BMU  1993        0.0
23           AFG       BTN  1993        0.0
24           AFG       BOL  1993        2.0
25           AFG       BIH  1993        2.0
26           AFG       BWA  1993        0.0
27           AFG       BRA  1993       47.0
28           AFG       BRN  1993        0.0
29           AFG       BGR  1993      178.0
...          ...       ...   ...        ...
267955       ZWE       TKL  2003        0.0
267956       ZWE       TON  2003        1.0
267957       ZWE       TTO  2003        0.0
267958       ZWE       TUN  2003        0.0
267959       ZWE       TUR  2003       11.0
267960       ZWE       TKM  2003        0.0
267961       ZWE       TCA  2003        0.0
267962       ZWE       TUV  2003        0.0
267963       ZWE       UGA  2003        7.0
267964       ZWE       UKR  2003      835.0
267965       ZWE       ARE  2003        0.0
267966       ZWE       GBR  2003    49791.0
267967       ZWE       USA  2003    12203.0
267968       ZWE       URY  2003        0.0
267969       ZWE       UZB  2003        0.0
267970       ZWE       VUT  2003        2.0
267971       ZWE       VEN  2003       13.0
267972       ZWE       VNM  2003        2.0
267973       ZWE       VIR  2003        0.0
267974       ZWE       VGB  2003        0.0
267975       ZWE       WLF  2003        0.0
267976       ZWE       PSE  2003        0.0
267977       ZWE       YEM  2003        0.0
267978       ZWE       ZMB  2003    31538.0
267979       ZWE       ZWE  2003        0.0
267980       NaN       NaN  2003        NaN
267981       NaN       NaN  2003        NaN
267982       NaN       NaN  2003        NaN
267983       NaN       NaN  2003        NaN
267984       NaN       NaN  2003        NaN

[267985 rows x 4 columns]

In [20]:
df_merged = pd.merge(df_main,df_mig_melt, how='left', on =['home_code', 'host_code', 'year'])

In [21]:
df_merged

,home,host,year,fdi,home_code,host_code,region,income_group,scoreproced,minorinvest,...,north-south,south-north,south-south,home_lock,host_lock,trade_lock,lang,union_partner,NAFTA,migration
0,Albania,Afghanistan,1993,NaN,ALB,AFG,NaN,NaN,NaN,NaN,...,1,0,0,0,1,1,0,0,0,3.0
1,Algeria,Afghanistan,1993,NaN,DZA,AFG,NaN,NaN,NaN,NaN,...,0,0,1,0,1,1,0,0,0,33.0
2,American Samoa,Afghanistan,1993,NaN,ASM,AFG,NaN,NaN,NaN,NaN,...,0,0,1,0,1,1,0,0,0,1.0
3,Angola,Afghanistan,1993,NaN,AGO,AFG,NaN,NaN,NaN,NaN,...,0,0,1,0,1,1,0,0,0,4.0
4,Anguilla,Afghanistan,1993,NaN,AIA,AFG,NaN,NaN,NaN,NaN,...,0,0,1,0,1,1,0,0,0,0.0
5,Antigua and Barbuda,Afghanistan,1993,NaN,ATG,AFG,NaN,NaN,NaN,NaN,...,0,0,1,0,1,1,0,0,0,0.0
6,Argentina,Afghanistan,1993,NaN,ARG,AFG,NaN,NaN,NaN,NaN,...,0,0,1,0,1,1,0,0,0,0.0
7,Armenia,Afghanistan,1993,NaN,ARM,AFG,NaN,NaN,NaN,NaN,...,0,0,1,1,1,1,0,0,0,0.0
8,Aruba,Afghanistan,1993,NaN,ABW,AFG,NaN,NaN,NaN,NaN,...,0,0,1,0,1,1,0,0,0,0.0
9,Australia,Afghanistan,1993,NaN,AUS,AFG,NaN,NaN,NaN,NaN,...,1,0,0,0,1,1,0,0,0,22.0
10,Austria,Afghanistan,1993,NaN,AUT,AFG,NaN,NaN,NaN,NaN,...,1,0,0,1,1,1,0,0,0,3.0
11,Azerbaijan,Afghanistan,1993,NaN,AZE,AFG,NaN,NaN,NaN,NaN,...,0,0,1,1,1,1,0,0,0,0.0
12,Bahamas,Afghanistan,1993,NaN,BHS,AFG,NaN,NaN,NaN,NaN,...,0,0,1,0,1,1,0,0,0,0.0
13,Bahrain,Afghanistan,1993,NaN,BHR,AFG,NaN,NaN,NaN,NaN,...,0,0,1,0,1,1,0,0,0,0.0
14,Bangladesh,Afghanistan,1993,NaN,BGD,AFG,NaN,NaN,NaN,NaN,...,0,0,1,0,1,1,0,0,0,31302.0
15,Barbados,Afghanistan,1993,NaN,BRB,AFG,NaN,NaN,NaN,NaN,...,0,0,1,0,1,1,0,0,0,0.0
16,Belarus,Afghanistan,1993,NaN,BLR,AFG,NaN,NaN,NaN,NaN,...,0,0,1,1,1,1,0,0,0,2.0
17,Belgium,Afghanistan,1993,NaN,BEL,AFG,NaN,NaN,NaN,NaN,...,1,0,0,0,1,1,0,0,0,0.0
18,Belize,Afghanistan,1993,NaN,BLZ,AFG,NaN,NaN,NaN,NaN,...,0,0,1,0,1,1,0,0,0,0.0
19,Benin,Afghanistan,1993,NaN,BEN,AFG,NaN,NaN,NaN,NaN,...,0,0,1,0,1,1,0,0,0,2.0
20,Bermuda,Afghanistan,1993,NaN,BMU,AFG,NaN,NaN,NaN,NaN,...,1,0,0,0,1,1,0,0,0,0.0
21,Bhutan,Afghanistan,1993,NaN,BTN,AFG,NaN,NaN,NaN,NaN,...,0,0,1,1,1,1,0,0,0,104.0
22,"Bolivia, Plurinational State of",Afghanistan,1993,NaN,BOL,AFG,NaN,NaN,NaN,NaN,...,0,0,1,1,1,1,0,0,0,0.0
23,Bosnia and Herzegovina,Afghanistan,1993,NaN,BIH,AFG,NaN,NaN,NaN,NaN,...,1,0,0,0,1,1,0,0,0,9.0
24,Botswana,Afghanistan,1993,NaN,BWA,AFG,NaN,NaN,NaN,NaN,...,0,0,1,1,1,1,0,0,0,1.0
25,Brazil,Afghanistan,1993,NaN,BRA,AFG,NaN,NaN,NaN,NaN,...,0,0,1,0,1,1,0,0,0,0.0
26,British Indian Ocean Territory,Afghanistan,1993,NaN,BIOT,AFG,NaN,NaN,NaN,NaN,...,0,0,1,0,1,1,0,0,0,NaN
27,British Virgin Islands,Afghanistan,1993,NaN,VGB,AFG,NaN,NaN,NaN,NaN,...,0,0,1,0,1,1,0,0,0,0.0
28,Brunei Darussalam,Afghanistan,1993,NaN,BRN,AFG,NaN,NaN,NaN,NaN,...,0,0,1,0,1,1,0,0,0,524.0
29,Bulgaria,Afghanistan,1993,NaN,BGR,AFG,NaN,NaN,NaN,NaN,...,1,0,0,0,1,1,0,0,0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1055720,Sweden,Zimbabwe,2017,NaN,SWE,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,1,0,0,0,1,1,0,0,0,NaN
1055721,Switzerland,Zimbabwe,2017,NaN,CHE,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,1,0,0,1,1,1,0,0,0,NaN
1055722,Syrian Arab Republic,Zimbabwe,2017,NaN,SYR,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,0,1,1,0,0,0,NaN
1055723,São Tomé and Principe,Zimbabwe,2017,NaN,STP,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,0,1,1,0,0,0,NaN
1055724,Taiwan Province of China,Zimbabwe,2017,NaN,TWN,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,1,0,0,0,1,1,0,0,0,NaN
1055725,Tajikistan,Zimbabwe,2017,NaN,TJK,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,1,1,1,0,0,0,NaN
1055726,Thailand,Zimbabwe,2017,NaN,THA,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,0,1,1,0,0,0,NaN
1055727,The FYR of Macedonia,Zimbabwe,2017,NaN,MKD,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,1,0,0,1,1,1,0,0,0,NaN
1055728,Timor-Leste,Zimbabwe,2017,NaN,TLS,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,0,1,1,1,0,0,NaN
1055729,Togo,Zimbabwe,2017,NaN,TGO,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,0,1,1,0,0,0,NaN
1055730,Tokelau,Zimbabwe,2017,NaN,TKL,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,0,1,1,1,0,0,NaN
1055731,Tonga,Zimbabwe,2017,NaN,TON,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,0,1,1,1,0,0,NaN
1055732,Trinidad and Tobago,Zimbabwe,2017,NaN,TTO,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,0,1,1,1,0,0,NaN
1055733,Tunisia,Zimbabwe,2017,NaN,TUN,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,0,1,1,0,0,0,NaN
1055734,Turkey,Zimbabwe,2017,NaN,TUR,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,1,0,0,0,1,1,0,0,0,NaN
1055735,Turks and Caicos Islands,Zimbabwe,2017,NaN,TCA,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,0,1,1,1,0,0,NaN
1055736,Tuvalu,Zimbabwe,2017,NaN,TUV,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,0,1,1,1,0,0,NaN
1055737,US Virgin Islands,Zimbabwe,2017,NaN,VIR,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,0,1,1,1,0,0,NaN
1055738,Uganda,Zimbabwe,2017,NaN,UGA,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,1,1,1,1,0,0,NaN
1055739,Ukraine,Zimbabwe,2017,NaN,UKR,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,0,1,1,0,0,0,NaN
1055740,United Arab Emirates,Zimbabwe,2017,NaN,ARE,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,0,1,1,0,0,0,NaN
1055741,United Kingdom,Zimbabwe,2017,NaN,GBR,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,1,0,0,0,1,1,1,0,0,NaN
1055742,United Rep. of Tanzania,Zimbabwe,2017,NaN,TZA,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,0,1,1,1,0,0,NaN
1055743,United States,Zimbabwe,2017,NaN,USA,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,1,0,0,0,1,1,1,0,0,NaN
1055744,Uruguay,Zimbabwe,2017,NaN,URY,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,0,1,1,0,0,0,NaN
1055745,Vanuatu,Zimbabwe,2017,NaN,VUT,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,0,1,1,0,0,0,NaN
1055746,"Venezuela, Bolivarian Rep. of",Zimbabwe,2017,NaN,VEN,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,0,1,1,0,0,0,NaN
1055747,Viet Nam,Zimbabwe,2017,NaN,VNM,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,0,1,1,0,0,0,NaN
1055748,Yemen,Zimbabwe,2017,NaN,YEM,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,0,1,1,0,0,0,NaN
1055749,Zambia,Zimbabwe,2017,NaN,ZMB,ZWE,Sub-Saharan Africa,Low income,80.0,53.33,...,0,0,1,1,1,1,1,0,0,NaN

In [22]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1055750 entries, 0 to 1055749
Data columns (total 66 columns):
home                 1055750 non-null object
host                 1055750 non-null object
year                 1055750 non-null int64
fdi                  65205 non-null float64
home_code            1055750 non-null object
host_code            1055750 non-null object
region               492000 non-null object
income_group         492000 non-null object
scoreproced          432755 non-null float64
minorinvest          432755 non-null float64
enfcontract          492000 non-null float64
paytax               432755 non-null float64
minorinvest_lag      395855 non-null float64
diff_minorinvest     395855 non-null float64
distance             993550 non-null float64
uncertainty          182042 non-null float64
home_gdp             953660 non-null float64
host_gdp             953660 non-null float64
couprisk             874940 non-null float64
couprisk_lag         839680 non-null float64
pt_attempt           874940 non-null float64
pt_attempt_lag       839680 non-null float64
prev_conflict        874940 non-null float64
prev_conflict_lag    839680 non-null float64
pctile_risk          874940 non-null float64
pctile_risk_lag      839680 non-null float64
diff_couprisk        839680 non-null float64
fdi_lag              65205 non-null float64
diff_fdi             58546 non-null float64
export               377483 non-null float64
home_EU              1055750 non-null int64
home_eurozone        1055750 non-null int64
host_EU              1055750 non-null int64
host_eurozone        1055750 non-null int64
EU_partner           1055750 non-null int64
eurozone_partner     1055750 non-null int64
home_asean           1055750 non-null int64
host_asean           1055750 non-null int64
home_mercosour       1055750 non-null int64
host_mercosour       1055750 non-null int64
asean_partner        1055750 non-null int64
mercosour_partner    1055750 non-null int64
tariff_avg           437258 non-null float64
tariff_w_avg         437258 non-null float64
uncertainty_lag      169039 non-null float64
uncertainty_lag2     156036 non-null float64
home_gdp_capita      953250 non-null float64
host_gdp_capita      953250 non-null float64
partner_directed     1055750 non-null object
partner              1055750 non-null object
home_OECD            1055750 non-null int64
host_OECD            1055750 non-null int64
OECD_partner         1055750 non-null int64
home_north           1055750 non-null int64
host_north           1055750 non-null int64
north-north          1055750 non-null int64
north-south          1055750 non-null int64
south-north          1055750 non-null int64
south-south          1055750 non-null int64
home_lock            1055750 non-null int64
host_lock            1055750 non-null int64
trade_lock           1055750 non-null int64
lang                 1055750 non-null int64
union_partner        1055750 non-null int64
NAFTA                1055750 non-null int64
migration            205030 non-null float64
dtypes: float64(30), int64(28), object(8)
memory usage: 539.7+ MB

In [23]:
df_merged.to_csv(directory +'merged_COPY_FINAL5.csv',index = False)