In [21]:
import pandas as pd
import numpy as np
from itertools import product
import time
import os
import re
from random import randint
from pytrends.request import TrendReq

In [2]:
country_code_cur= pd.read_csv("https://gist.githubusercontent.com/HarishChaudhari/4680482/raw/b61a5bdf5f3d5c69399f9d9e592c4896fd0dc53c/country-code-to-currency-code-mapping.csv")

In [3]:
code_alpha3 = pd.read_csv("https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.csv")

In [4]:
OECD_countries = ['Australia', 'Austria','Belgium','Canada', 'Chile','Czech Republic', 'Czechia','Denmark','Estonia',
                 'Finland','France','Germany','Greece','Hungary','Iceland','Israel','Italy','Japan', 'Korea', 'Latvia',
                 'Lithuania','Luxembourg','Mexico','Netherlands','New Zealand','Norway','Poland','Portugal','Slovak Republic',
                 'Slovenia','Spain','Sweden','Switzerland', 'Turkey', 'United Kingdom','United States']

In [5]:
directory  = "/media/sony/0CA83E99A83E80EE/Chris/Bocconi/Thesis/Data_copy/Data/Trends/"

In [6]:
len(OECD_countries )

36

In [7]:
OECD_dict = {'Australia': 'AUS', 'Austria':'AUT','Belgium':'BEL','Canada': 'CAN', 'Chile': 'CHL',
                    'Czech Republic': 'CZE','Denmark': 'DNK','Estonia': 'EST',
                 'Finland': 'FIN','France': 'FRA','Germany': 'DEU','Greece':'GRC','Hungary':'HUN',
                    'Iceland':'ISL','Israel':'ISR','Italy':'ITA','Japan':'JPN', 'Korea': 'KOR', 'Latvia':'LVA',
                 'Lithuania':'LTU','Luxembourg':'LUX','Mexico': 'MEX','Netherlands':'NLD','New Zealand':'NZL',
                    'Norway':'NOR','Poland':'POL','Portugal':'PRT','Slovakia':'SVK',
                 'Slovenia':'SVN','Spain':'ESP','Sweden':'SWE','Switzerland':'CHE', 
                    'Turkey':'TUR', 'United Kingdom':'GBR','United States':'USA'}

In [8]:
Others_dict = {'Afghanistan':'AFG','Albania':'ALB','Algeria':'DZA',
                     'Andorra':'AND','Angola':'AGO','Argentina':'ARG',
                     'Aruba':'ABW','Azerbaijan':'AZE','Bahamas':'BHS',
                     'Bahrain':'BHR','Bangladesh':'BGD','Barbados':'BRB',
                     'Belize':'BLZ', 'Bermuda': 'BMU', 'Bolivia': 'BOL',
                     'Botswana': 'BWA', 'Brazil':'BRA','Brunei Darussalam': 'BRN',
                     'Bulgaria':'BGR','Cambodia':'KHM','Cameroon':'CMR',
                      'Cayman Islands':'CYM', 'China': 'CHN', 'Colombia': 'COL',
                     'Costa Rica':'CRI', 'Croatia':'HRV', 'Curacao': 'CUW',
                     'Cyprus': 'CYP', "Cote d'Ivoire":'CIV', 'Ecuador':'ECU',
                     'Egypt':'EGY', 'Ethiopia':'ETH','French Guiana':'GUF',
                     'French Polynesia': 'PYF', 'Gabon': 'GAB','Gambia':'GMB',
                     'Georgia':'GEO','Ghana':'GHA','Greenland':'GRL',
                     'Guadeloupe': 'GLP','Guam':'GUM','Guatemala':'GTM',
                     'Guyana': 'GUY','Honduras':'HND','Hong Kong':'HKG',
                     'India': 'IND', 'Indonesia': 'IDN','Iran':'IRN',
                     'Ireland':'IE','Jamaica':'JAM','Jordan':'JOR',
                      'Kazakhstan':'KAZ','Kenya':'KEN','Kuwait':'KWT',
                     "Laos": 'LAO',
                     'Lebanon':'LBN','Libya':'LBY', 'Macao':'MAC',
                      'Macedonia':'MKD','Malaysia':'MYS', 'Maldives':'MDV',
                     'Malta':'MLT', 'Marshall Islands':'MHL', 'Mauritius':'MUS',
                     'Monaco':'MCO','Morocco':'MAR', 'Myanmar': 'MMR',
                     'Namibia': 'NAM', 'Nepal':'NPL','Nicaragua':'NIC','Niger'
                     'Nigeria':'NGA','Oman':'OMN','Pakistan':'PAK',
                     'Panama':'PAN','Paraguay':'PRY','Peru':'PER','Philippines':'PHL',
                     'Puerto Rico': 'PRI', 'Qatar':'QAT','Romania':'ROU',
                     'Russia': 'RUS','Rwanda': 'RWA','Saudi Arabia':'SAU',
                     'Senegal':'SEN','Serbia':'SRB','Seychelles': 'SYC', 
                      'Singapore': 'SGP', 'South Africa': 'ZAF', 'Sri Lanka': 'LKA', 
                      'Syria': 'SYR','Taiwan':'TWN', 'Thailand': 'THA', 
                      'Trinidad and Tobago':'TTO', 'Tunisia': 'TUN', 'Ukraine' :'UKR',
                      'United Arab Emirates': 'ARE', 'Uruguay':'URY', 'Venezuela':'VEN',
                      'Viet Nam':'VNM'
                     }

In [9]:
combine_dict = dict()
combine_dict.update(Others_dict)
combine_dict.update(OECD_dict)

In [10]:
list(combine_dict.keys())

['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Argentina',
 'Aruba',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belize',
 'Bermuda',
 'Bolivia',
 'Botswana',
 'Brazil',
 'Brunei Darussalam',
 'Bulgaria',
 'Cambodia',
 'Cameroon',
 'Cayman Islands',
 'China',
 'Colombia',
 'Costa Rica',
 'Croatia',
 'Curacao',
 'Cyprus',
 "Cote d'Ivoire",
 'Ecuador',
 'Egypt',
 'Ethiopia',
 'French Guiana',
 'French Polynesia',
 'Gabon',
 'Gambia',
 'Georgia',
 'Ghana',
 'Greenland',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guyana',
 'Honduras',
 'Hong Kong',
 'India',
 'Indonesia',
 'Iran',
 'Ireland',
 'Jamaica',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kuwait',
 'Laos',
 'Lebanon',
 'Libya',
 'Macao',
 'Macedonia',
 'Malaysia',
 'Maldives',
 'Malta',
 'Marshall Islands',
 'Mauritius',
 'Monaco',
 'Morocco',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Nicaragua',
 'NigerNigeria',
 'Oman',
 'Pakistan',
 'Panama',
 'Paraguay',
 'Peru',
 'Philippines',
 'Puerto Rico',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Singapore',
 'South Africa',
 'Sri Lanka',
 'Syria',
 'Taiwan',
 'Thailand',
 'Trinidad and Tobago',
 'Tunisia',
 'Ukraine',
 'United Arab Emirates',
 'Uruguay',
 'Venezuela',
 'Viet Nam',
 'Australia',
 'Austria',
 'Belgium',
 'Canada',
 'Chile',
 'Czech Republic',
 'Denmark',
 'Estonia',
 'Finland',
 'France',
 'Germany',
 'Greece',
 'Hungary',
 'Iceland',
 'Israel',
 'Italy',
 'Japan',
 'Korea',
 'Latvia',
 'Lithuania',
 'Luxembourg',
 'Mexico',
 'Netherlands',
 'New Zealand',
 'Norway',
 'Poland',
 'Portugal',
 'Slovakia',
 'Slovenia',
 'Spain',
 'Sweden',
 'Switzerland',
 'Turkey',
 'United Kingdom',
 'United States']

In [11]:
code_country_dict = dict( [(value, key) for key, value in combine_dict.items()] )

In [12]:
code_country_dict

{'AFG': 'Afghanistan',
 'ALB': 'Albania',
 'DZA': 'Algeria',
 'AND': 'Andorra',
 'AGO': 'Angola',
 'ARG': 'Argentina',
 'ABW': 'Aruba',
 'AZE': 'Azerbaijan',
 'BHS': 'Bahamas',
 'BHR': 'Bahrain',
 'BGD': 'Bangladesh',
 'BRB': 'Barbados',
 'BLZ': 'Belize',
 'BMU': 'Bermuda',
 'BOL': 'Bolivia',
 'BWA': 'Botswana',
 'BRA': 'Brazil',
 'BRN': 'Brunei Darussalam',
 'BGR': 'Bulgaria',
 'KHM': 'Cambodia',
 'CMR': 'Cameroon',
 'CYM': 'Cayman Islands',
 'CHN': 'China',
 'COL': 'Colombia',
 'CRI': 'Costa Rica',
 'HRV': 'Croatia',
 'CUW': 'Curacao',
 'CYP': 'Cyprus',
 'CIV': "Cote d'Ivoire",
 'ECU': 'Ecuador',
 'EGY': 'Egypt',
 'ETH': 'Ethiopia',
 'GUF': 'French Guiana',
 'PYF': 'French Polynesia',
 'GAB': 'Gabon',
 'GMB': 'Gambia',
 'GEO': 'Georgia',
 'GHA': 'Ghana',
 'GRL': 'Greenland',
 'GLP': 'Guadeloupe',
 'GUM': 'Guam',
 'GTM': 'Guatemala',
 'GUY': 'Guyana',
 'HND': 'Honduras',
 'HKG': 'Hong Kong',
 'IND': 'India',
 'IDN': 'Indonesia',
 'IRN': 'Iran',
 'IE': 'Ireland',
 'JAM': 'Jamaica',
 'JOR': 'Jordan',
 'KAZ': 'Kazakhstan',
 'KEN': 'Kenya',
 'KWT': 'Kuwait',
 'LAO': 'Laos',
 'LBN': 'Lebanon',
 'LBY': 'Libya',
 'MAC': 'Macao',
 'MKD': 'Macedonia',
 'MYS': 'Malaysia',
 'MDV': 'Maldives',
 'MLT': 'Malta',
 'MHL': 'Marshall Islands',
 'MUS': 'Mauritius',
 'MCO': 'Monaco',
 'MAR': 'Morocco',
 'MMR': 'Myanmar',
 'NAM': 'Namibia',
 'NPL': 'Nepal',
 'NIC': 'Nicaragua',
 'NGA': 'NigerNigeria',
 'OMN': 'Oman',
 'PAK': 'Pakistan',
 'PAN': 'Panama',
 'PRY': 'Paraguay',
 'PER': 'Peru',
 'PHL': 'Philippines',
 'PRI': 'Puerto Rico',
 'QAT': 'Qatar',
 'ROU': 'Romania',
 'RUS': 'Russia',
 'RWA': 'Rwanda',
 'SAU': 'Saudi Arabia',
 'SEN': 'Senegal',
 'SRB': 'Serbia',
 'SYC': 'Seychelles',
 'SGP': 'Singapore',
 'ZAF': 'South Africa',
 'LKA': 'Sri Lanka',
 'SYR': 'Syria',
 'TWN': 'Taiwan',
 'THA': 'Thailand',
 'TTO': 'Trinidad and Tobago',
 'TUN': 'Tunisia',
 'UKR': 'Ukraine',
 'ARE': 'United Arab Emirates',
 'URY': 'Uruguay',
 'VEN': 'Venezuela',
 'VNM': 'Viet Nam',
 'AUS': 'Australia',
 'AUT': 'Austria',
 'BEL': 'Belgium',
 'CAN': 'Canada',
 'CHL': 'Chile',
 'CZE': 'Czech Republic',
 'DNK': 'Denmark',
 'EST': 'Estonia',
 'FIN': 'Finland',
 'FRA': 'France',
 'DEU': 'Germany',
 'GRC': 'Greece',
 'HUN': 'Hungary',
 'ISL': 'Iceland',
 'ISR': 'Israel',
 'ITA': 'Italy',
 'JPN': 'Japan',
 'KOR': 'Korea',
 'LVA': 'Latvia',
 'LTU': 'Lithuania',
 'LUX': 'Luxembourg',
 'MEX': 'Mexico',
 'NLD': 'Netherlands',
 'NZL': 'New Zealand',
 'NOR': 'Norway',
 'POL': 'Poland',
 'PRT': 'Portugal',
 'SVK': 'Slovakia',
 'SVN': 'Slovenia',
 'ESP': 'Spain',
 'SWE': 'Sweden',
 'CHE': 'Switzerland',
 'TUR': 'Turkey',
 'GBR': 'United Kingdom',
 'USA': 'United States'}

In [13]:
ser_codes = pd.Series(list(combine_dict.values()))
ser_codes.head()

0    AFG
1    ALB
2    DZA
3    AND
4    AGO
dtype: object

In [14]:
ser_oecd_codes = pd.Series(list(OECD_dict.values()))
ser_oecd_codes.head()

0    AUS
1    AUT
2    BEL
3    CAN
4    CHL
dtype: object

In [15]:
df_combination = pd.DataFrame(list(product(ser_codes,ser_codes)))
df_combination = df_combination [ df_combination[0] != df_combination[1] ]
df_combination = df_combination.rename(columns ={0: 'home', 1: 'host'})

In [16]:
df_oecd = pd.DataFrame(list(product(ser_oecd_codes,ser_oecd_codes)))
df_oecd = df_oecd [ df_oecd[0] != df_oecd[1] ]
df_oecd = df_oecd.rename(columns ={0: 'home', 1: 'host'})

In [17]:
len(df_oecd)

1190

In [19]:
already_scraped = dict()
for path in os.listdir(directory):
    country_codes = re.findall(r'([A-Z]+)', path)
    try:
        already_scraped[country_codes[0]].append(country_codes[1])
    except:
        already_scraped[country_codes[0]] = [country_codes[1]]

In [23]:
pytrends = TrendReq(hl='en-US', tz=360)
counter = 0
for index, row in df_oecd.iterrows():
    home_3dig = row[0]
    home_2dig = code_alpha3[code_alpha3['alpha-3'] == home_3dig].iloc[0,1]
    host_3dig = row[1]
    try:
        temp = already_scraped[home_3dig]
    except:
        already_scraped[home_3dig] = []
    if host_3dig in already_scraped[home_3dig]:
        continue
    try:
        already_scraped[home_3dig].append(host_3dig)
    except:
        already_scraped[country_codes[0]] = [country_codes[1]]
        
    search_term = code_country_dict[host_3dig]
    geo_loc = home_2dig
    
    pytrends.build_payload(kw_list = [search_term], geo = geo_loc, timeframe ='all', cat = 19)
    
    df_trend = pytrends.interest_over_time()
    df_trend['home'] = home_3dig
    df_trend['host'] = host_3dig
    del df_trend['isPartial']
    df_trend.to_csv(directory +home_3dig +'_' +host_3dig+'.csv', index=True)

    print(home_3dig)
    print(host_3dig)
    print(search_term)
    print('.............')
    if counter % 7 == 0:
        print(counter)
        time.sleep(16)
    elif counter % 25 == 0:
        print(counter)
        time.sleep(60)        
    else:
    
        time.sleep(18)
    counter += 1

CHE
SWE
Sweden
.............
0
CHE
TUR
Turkey
.............
CHE
GBR
United Kingdom
.............
CHE
USA
United States
.............
TUR
AUS
Australia
.............
TUR
AUT
Austria
.............
TUR
BEL
Belgium
.............
TUR
CAN
Canada
.............
7
TUR
CHL
Chile
.............
TUR
CZE
Czech Republic
.............
TUR
DNK
Denmark
.............
TUR
EST
Estonia
.............
TUR
FIN
Finland
.............
TUR
FRA
France
.............
TUR
DEU
Germany
.............
14
TUR
GRC
Greece
.............
TUR
HUN
Hungary
.............
TUR
ISL
Iceland
.............
TUR
ISR
Israel
.............
TUR
ITA
Italy
.............
TUR
JPN
Japan
.............
TUR
KOR
Korea
.............
21
TUR
LVA
Latvia
.............
TUR
LTU
Lithuania
.............
TUR
LUX
Luxembourg
.............
TUR
MEX
Mexico
.............
25
TUR
NLD
Netherlands
.............
TUR
NZL
New Zealand
.............
TUR
NOR
Norway
.............
28
TUR
POL
Poland
.............
TUR
PRT
Portugal
.............
TUR
SVK
Slovakia
.............
TUR
SVN
Slovenia
.............
TUR
ESP
Spain
.............
TUR
SWE
Sweden
.............
TUR
CHE
Switzerland
.............
35
TUR
GBR
United Kingdom
.............
TUR
USA
United States
.............
GBR
AUS
Australia
.............
GBR
AUT
Austria
.............
GBR
BEL
Belgium
.............
GBR
CAN
Canada
.............
GBR
CHL
Chile
.............
42
GBR
CZE
Czech Republic
.............
GBR
DNK
Denmark
.............
GBR
EST
Estonia
.............
GBR
FIN
Finland
.............
GBR
FRA
France
.............
GBR
DEU
Germany
.............
GBR
GRC
Greece
.............
49
GBR
HUN
Hungary
.............
50
GBR
ISL
Iceland
.............
GBR
ISR
Israel
.............
GBR
ITA
Italy
.............
GBR
JPN
Japan
.............
GBR
KOR
Korea
.............
GBR
LVA
Latvia
.............
56
GBR
LTU
Lithuania
.............
GBR
LUX
Luxembourg
.............
GBR
MEX
Mexico
.............
GBR
NLD
Netherlands
.............
GBR
NZL
New Zealand
.............
GBR
NOR
Norway
.............
GBR
POL
Poland
.............
63
GBR
PRT
Portugal
.............
GBR
SVK
Slovakia
.............
GBR
SVN
Slovenia
.............
GBR
ESP
Spain
.............
GBR
SWE
Sweden
.............
GBR
CHE
Switzerland
.............
GBR
TUR
Turkey
.............
70
GBR
USA
United States
.............
USA
AUS
Australia
.............
USA
AUT
Austria
.............
USA
BEL
Belgium
.............
USA
CAN
Canada
.............
75
USA
CHL
Chile
.............
USA
CZE
Czech Republic
.............
77
USA
DNK
Denmark
.............
USA
EST
Estonia
.............
USA
FIN
Finland
.............
USA
FRA
France
.............
USA
DEU
Germany
.............
USA
GRC
Greece
.............
USA
HUN
Hungary
.............
84
USA
ISL
Iceland
.............
USA
ISR
Israel
.............
USA
ITA
Italy
.............
USA
JPN
Japan
.............
USA
KOR
Korea
.............
USA
LVA
Latvia
.............
USA
LTU
Lithuania
.............
91
USA
LUX
Luxembourg
.............
USA
MEX
Mexico
.............
USA
NLD
Netherlands
.............
USA
NZL
New Zealand
.............
USA
NOR
Norway
.............
USA
POL
Poland
.............
USA
PRT
Portugal
.............
98
USA
SVK
Slovakia
.............
USA
SVN
Slovenia
.............
100
USA
ESP
Spain
.............
USA
SWE
Sweden
.............
USA
CHE
Switzerland
.............
USA
TUR
Turkey
.............
USA
GBR
United Kingdom
.............
105

In [342]:
code_alpha3[code_alpha3.name == 'Estonia']

,name,alpha-2,alpha-3,country-code,iso_3166-2,region,sub-region,intermediate-region,region-code,sub-region-code,intermediate-region-code
69,Estonia,EE,EST,233,ISO 3166-2:EE,Europe,Northern Europe,NaN,150.0,154.0,NaN

In [41]:
country_code_cur= country_code_cur.set_index('Country').sort_index()

In [37]:
code_alpha3 = pd.read_csv("https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.csv")

In [38]:
code_alpha3

,name,alpha-2,alpha-3,country-code,iso_3166-2,region,sub-region,intermediate-region,region-code,sub-region-code,intermediate-region-code
0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,Asia,Southern Asia,NaN,142.0,34.0,NaN
1,Åland Islands,AX,ALA,248,ISO 3166-2:AX,Europe,Northern Europe,NaN,150.0,154.0,NaN
2,Albania,AL,ALB,8,ISO 3166-2:AL,Europe,Southern Europe,NaN,150.0,39.0,NaN
3,Algeria,DZ,DZA,12,ISO 3166-2:DZ,Africa,Northern Africa,NaN,2.0,15.0,NaN
4,American Samoa,AS,ASM,16,ISO 3166-2:AS,Oceania,Polynesia,NaN,9.0,61.0,NaN
5,Andorra,AD,AND,20,ISO 3166-2:AD,Europe,Southern Europe,NaN,150.0,39.0,NaN
6,Angola,AO,AGO,24,ISO 3166-2:AO,Africa,Sub-Saharan Africa,Middle Africa,2.0,202.0,17.0
7,Anguilla,AI,AIA,660,ISO 3166-2:AI,Americas,Latin America and the Caribbean,Caribbean,19.0,419.0,29.0
8,Antarctica,AQ,ATA,10,ISO 3166-2:AQ,NaN,NaN,NaN,NaN,NaN,NaN
9,Antigua and Barbuda,AG,ATG,28,ISO 3166-2:AG,Americas,Latin America and the Caribbean,Caribbean,19.0,419.0,29.0
10,Argentina,AR,ARG,32,ISO 3166-2:AR,Americas,Latin America and the Caribbean,South America,19.0,419.0,5.0
11,Armenia,AM,ARM,51,ISO 3166-2:AM,Asia,Western Asia,NaN,142.0,145.0,NaN
12,Aruba,AW,ABW,533,ISO 3166-2:AW,Americas,Latin America and the Caribbean,Caribbean,19.0,419.0,29.0
13,Australia,AU,AUS,36,ISO 3166-2:AU,Oceania,Australia and New Zealand,NaN,9.0,53.0,NaN
14,Austria,AT,AUT,40,ISO 3166-2:AT,Europe,Western Europe,NaN,150.0,155.0,NaN
15,Azerbaijan,AZ,AZE,31,ISO 3166-2:AZ,Asia,Western Asia,NaN,142.0,145.0,NaN
16,Bahamas,BS,BHS,44,ISO 3166-2:BS,Americas,Latin America and the Caribbean,Caribbean,19.0,419.0,29.0
17,Bahrain,BH,BHR,48,ISO 3166-2:BH,Asia,Western Asia,NaN,142.0,145.0,NaN
18,Bangladesh,BD,BGD,50,ISO 3166-2:BD,Asia,Southern Asia,NaN,142.0,34.0,NaN
19,Barbados,BB,BRB,52,ISO 3166-2:BB,Americas,Latin America and the Caribbean,Caribbean,19.0,419.0,29.0
20,Belarus,BY,BLR,112,ISO 3166-2:BY,Europe,Eastern Europe,NaN,150.0,151.0,NaN
21,Belgium,BE,BEL,56,ISO 3166-2:BE,Europe,Western Europe,NaN,150.0,155.0,NaN
22,Belize,BZ,BLZ,84,ISO 3166-2:BZ,Americas,Latin America and the Caribbean,Central America,19.0,419.0,13.0
23,Benin,BJ,BEN,204,ISO 3166-2:BJ,Africa,Sub-Saharan Africa,Western Africa,2.0,202.0,11.0
24,Bermuda,BM,BMU,60,ISO 3166-2:BM,Americas,Northern America,NaN,19.0,21.0,NaN
25,Bhutan,BT,BTN,64,ISO 3166-2:BT,Asia,Southern Asia,NaN,142.0,34.0,NaN
26,Bolivia (Plurinational State of),BO,BOL,68,ISO 3166-2:BO,Americas,Latin America and the Caribbean,South America,19.0,419.0,5.0
27,"Bonaire, Sint Eustatius and Saba",BQ,BES,535,ISO 3166-2:BQ,Americas,Latin America and the Caribbean,Caribbean,19.0,419.0,29.0
28,Bosnia and Herzegovina,BA,BIH,70,ISO 3166-2:BA,Europe,Southern Europe,NaN,150.0,39.0,NaN
29,Botswana,BW,BWA,72,ISO 3166-2:BW,Africa,Sub-Saharan Africa,Southern Africa,2.0,202.0,18.0
...,...,...,...,...,...,...,...,...,...,...,...
219,"Tanzania, United Republic of",TZ,TZA,834,ISO 3166-2:TZ,Africa,Sub-Saharan Africa,Eastern Africa,2.0,202.0,14.0
220,Thailand,TH,THA,764,ISO 3166-2:TH,Asia,South-eastern Asia,NaN,142.0,35.0,NaN
221,Timor-Leste,TL,TLS,626,ISO 3166-2:TL,Asia,South-eastern Asia,NaN,142.0,35.0,NaN
222,Togo,TG,TGO,768,ISO 3166-2:TG,Africa,Sub-Saharan Africa,Western Africa,2.0,202.0,11.0
223,Tokelau,TK,TKL,772,ISO 3166-2:TK,Oceania,Polynesia,NaN,9.0,61.0,NaN
224,Tonga,TO,TON,776,ISO 3166-2:TO,Oceania,Polynesia,NaN,9.0,61.0,NaN
225,Trinidad and Tobago,TT,TTO,780,ISO 3166-2:TT,Americas,Latin America and the Caribbean,Caribbean,19.0,419.0,29.0
226,Tunisia,TN,TUN,788,ISO 3166-2:TN,Africa,Northern Africa,NaN,2.0,15.0,NaN
227,Turkey,TR,TUR,792,ISO 3166-2:TR,Asia,Western Asia,NaN,142.0,145.0,NaN
228,Turkmenistan,TM,TKM,795,ISO 3166-2:TM,Asia,Central Asia,NaN,142.0,143.0,NaN
229,Turks and Caicos Islands,TC,TCA,796,ISO 3166-2:TC,Americas,Latin America and the Caribbean,Caribbean,19.0,419.0,29.0
230,Tuvalu,TV,TUV,798,ISO 3166-2:TV,Oceania,Polynesia,NaN,9.0,61.0,NaN
231,Uganda,UG,UGA,800,ISO 3166-2:UG,Africa,Sub-Saharan Africa,Eastern Africa,2.0,202.0,14.0
232,Ukraine,UA,UKR,804,ISO 3166-2:UA,Europe,Eastern Europe,NaN,150.0,151.0,NaN
233,United Arab Emirates,AE,ARE,784,ISO 3166-2:AE,Asia,Western Asia,NaN,142.0,145.0,NaN
234,United Kingdom of Great Britain and Northern I...,GB,GBR,826,ISO 3166-2:GB,Europe,Northern Europe,NaN,150.0,154.0,NaN
235,United States of America,US,USA,840,ISO 3166-2:US,Americas,Northern America,NaN,19.0,21.0,NaN
236,United States Minor Outlying Islands,UM,UMI,581,ISO 3166-2:UM,Oceania,Micronesia,NaN,9.0,57.0,NaN
237,Uruguay,UY,URY,858,ISO 3166-2:UY,Americas,Latin America and the Caribbean,South America,19.0,419.0,5.0
238,Uzbekistan,UZ,UZB,860,ISO 3166-2:UZ,Asia,Central Asia,NaN,142.0,143.0,NaN
239,Vanuatu,VU,VUT,548,ISO 3166-2:VU,Oceania,Melanesia,NaN,9.0,54.0,NaN
240,Venezuela (Bolivarian Republic of),VE,VEN,862,ISO 3166-2:VE,Americas,Latin America and the Caribbean,South America,19.0,419.0,5.0
241,Viet Nam,VN,VNM,704,ISO 3166-2:VN,Asia,South-eastern Asia,NaN,142.0,35.0,NaN
242,Virgin Islands (British),VG,VGB,92,ISO 3166-2:VG,Americas,Latin America and the Caribbean,Caribbean,19.0,419.0,29.0
243,Virgin Islands (U.S.),VI,VIR,850,ISO 3166-2:VI,Americas,Latin America and the Caribbean,Caribbean,19.0,419.0,29.0
244,Wallis and Futuna,WF,WLF,876,ISO 3166-2:WF,Oceania,Polynesia,NaN,9.0,61.0,NaN
245,Western Sahara,EH,ESH,732,ISO 3166-2:EH,Africa,Northern Africa,NaN,2.0,15.0,NaN
246,Yemen,YE,YEM,887,ISO 3166-2:YE,Asia,Western Asia,NaN,142.0,145.0,NaN
247,Zambia,ZM,ZMB,894,ISO 3166-2:ZM,Africa,Sub-Saharan Africa,Eastern Africa,2.0,202.0,14.0
248,Zimbabwe,ZW,ZWE,716,ISO 3166-2:ZW,Africa,Sub-Saharan Africa,Eastern Africa,2.0,202.0,14.0

In [76]:
s = code_alpha3[code_alpha3['alpha-3'] == 'BOL']
s = s.iloc[0,2]
s

'BOL'

,name,alpha-2,alpha-3,country-code,iso_3166-2,region,sub-region,intermediate-region,region-code,sub-region-code,intermediate-region-code
26,Bolivia (Plurinational State of),BO,BOL,68,ISO 3166-2:BO,Americas,Latin America and the Caribbean,South America,19.0,419.0,5.0

In [15]:
country_abrev = pd.read_html('https://www.ncbi.nlm.nih.gov/books/NBK7249/')

HTTPError: HTTP Error 403: Forbidden

In [272]:
doggy= 'Brexit'
cat = 19
geo_loc ='US'

In [273]:
pytrends.build_payload(kw_list = [doggy], geo = geo_loc,timeframe ='all', cat = 19)

In [274]:
df = pytrends.interest_over_time()

In [275]:
df['home'] ='US'

In [276]:
df['host'] = 'UK'
df

            Brexit isPartial home host
date
2004-01-01       0     False   US   UK
2004-02-01       0     False   US   UK
2004-03-01       0     False   US   UK
2004-04-01       0     False   US   UK
2004-05-01       0     False   US   UK
2004-06-01       0     False   US   UK
2004-07-01       0     False   US   UK
2004-08-01       0     False   US   UK
2004-09-01       0     False   US   UK
2004-10-01       0     False   US   UK
2004-11-01       0     False   US   UK
2004-12-01       0     False   US   UK
2005-01-01       0     False   US   UK
2005-02-01       0     False   US   UK
2005-03-01       0     False   US   UK
2005-04-01       0     False   US   UK
2005-05-01       0     False   US   UK
2005-06-01       0     False   US   UK
2005-07-01       0     False   US   UK
2005-08-01       0     False   US   UK
2005-09-01       0     False   US   UK
2005-10-01       0     False   US   UK
2005-11-01       0     False   US   UK
2005-12-01       0     False   US   UK
2006-01-01       0     False   US   UK
2006-02-01       0     False   US   UK
2006-03-01       0     False   US   UK
2006-04-01       0     False   US   UK
2006-05-01       0     False   US   UK
2006-06-01       0     False   US   UK
...            ...       ...  ...  ...
2017-02-01       4     False   US   UK
2017-03-01       6     False   US   UK
2017-04-01       4     False   US   UK
2017-05-01       3     False   US   UK
2017-06-01       4     False   US   UK
2017-07-01       2     False   US   UK
2017-08-01       2     False   US   UK
2017-09-01       3     False   US   UK
2017-10-01       3     False   US   UK
2017-11-01       3     False   US   UK
2017-12-01       3     False   US   UK
2018-01-01       2     False   US   UK
2018-02-01       3     False   US   UK
2018-03-01       3     False   US   UK
2018-04-01       2     False   US   UK
2018-05-01       2     False   US   UK
2018-06-01       3     False   US   UK
2018-07-01       5     False   US   UK
2018-08-01       2     False   US   UK
2018-09-01       3     False   US   UK
2018-10-01       4     False   US   UK
2018-11-01       7     False   US   UK
2018-12-01       9     False   US   UK
2019-01-01      16     False   US   UK
2019-02-01       9     False   US   UK
2019-03-01      18     False   US   UK
2019-04-01      11     False   US   UK
2019-05-01       7     False   US   UK
2019-06-01       4     False   US   UK
2019-07-01       2      True   US   UK

[187 rows x 4 columns]

In [233]:
df.to_csv(directory +'US_UK.csv', index=True)

In [277]:
del df['isPartial']

In [278]:
df

            Brexit home host
date
2004-01-01       0   US   UK
2004-02-01       0   US   UK
2004-03-01       0   US   UK
2004-04-01       0   US   UK
2004-05-01       0   US   UK
2004-06-01       0   US   UK
2004-07-01       0   US   UK
2004-08-01       0   US   UK
2004-09-01       0   US   UK
2004-10-01       0   US   UK
2004-11-01       0   US   UK
2004-12-01       0   US   UK
2005-01-01       0   US   UK
2005-02-01       0   US   UK
2005-03-01       0   US   UK
2005-04-01       0   US   UK
2005-05-01       0   US   UK
2005-06-01       0   US   UK
2005-07-01       0   US   UK
2005-08-01       0   US   UK
2005-09-01       0   US   UK
2005-10-01       0   US   UK
2005-11-01       0   US   UK
2005-12-01       0   US   UK
2006-01-01       0   US   UK
2006-02-01       0   US   UK
2006-03-01       0   US   UK
2006-04-01       0   US   UK
2006-05-01       0   US   UK
2006-06-01       0   US   UK
...            ...  ...  ...
2017-02-01       4   US   UK
2017-03-01       6   US   UK
2017-04-01       4   US   UK
2017-05-01       3   US   UK
2017-06-01       4   US   UK
2017-07-01       2   US   UK
2017-08-01       2   US   UK
2017-09-01       3   US   UK
2017-10-01       3   US   UK
2017-11-01       3   US   UK
2017-12-01       3   US   UK
2018-01-01       2   US   UK
2018-02-01       3   US   UK
2018-03-01       3   US   UK
2018-04-01       2   US   UK
2018-05-01       2   US   UK
2018-06-01       3   US   UK
2018-07-01       5   US   UK
2018-08-01       2   US   UK
2018-09-01       3   US   UK
2018-10-01       4   US   UK
2018-11-01       7   US   UK
2018-12-01       9   US   UK
2019-01-01      16   US   UK
2019-02-01       9   US   UK
2019-03-01      18   US   UK
2019-04-01      11   US   UK
2019-05-01       7   US   UK
2019-06-01       4   US   UK
2019-07-01       2   US   UK

[187 rows x 3 columns]